/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.kkmji.hibiscus.base;

import java.util.concurrent.ThreadLocalRandom;

import org.junit.Test;
import org.junit.jupiter.api.Assertions;

import dev.kkmji.hibiscus.base.utils.MathUtil;

public class MathUtilTest {

    @Test
    public void testRandomInt() {
        ThreadLocalRandom rnd = ThreadLocalRandom.current();

        for(int i = 0; i < 100; i++) {
            Assertions.assertDoesNotThrow(() -> MathUtil.randomInt(rnd.nextInt() * 100));
            Assertions.assertDoesNotThrow(() -> MathUtil.randomInt(-(rnd.nextInt() * 100)));
        }
    }


}